console.log("primeira linha \n segunda linha")
console.log("o meu nome é 'joao'")
console.log('o meu nome é "joao"')
console.log(`uma multiplicacao ${5*3}`)
console.log("O"+" meu "+" nome "+" é "+" joao")